name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
jobs:
  build-api:
    runs-on: ubuntu-20.04
    steps:
      # Build
      - uses: actions/checkout@v2
      - name: Add remote
        run: git remote add publish_remote https://github.com/ihm-tswow/site-2.git
      - name: Create dummy commit file
        run: touch __dummy.txt
      - name: Commit build files
        run: git add . && git config user.name test && git config user.email test && git commit -m "Bump"
      - name: Push to another repository
        uses: https://github.com/MischaPanch/github-action-push-to-another-repository.git@5fecbad518f01d5909109fa086043c7a3cb75821
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          destination-github-username: 'ihm-tswow'
          destination-repository-name: 'site-2'
          user-email: carles3@pina.cat
          target-branch: main