name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
jobs:
  build-api:
    runs-on: windows-2019
    steps:
      # Build
      - uses: actions/checkout@v2
      - name: Create dummy commit file
        run: echo . > __dummy.txt
      - run: Invoke-WebRequest -Uri "https://github.com/git-for-windows/git/releases/download/v2.36.1.windows.1/MinGit-2.36.1-64-bit.zip"-OutFile "out.zip"
      - run: tar -xf out.zip
      - name: Commit build files
        run: git add . && git config user.name test && git config user.email test && git commit -m "Bump"
      - name: Push
        run: mingw64/bin/git.exe push "https://ihm-tswow:${{secrets.NEW_TOKEN}}@github.com/ihm-tswow/site-2.git" -f HEAD:main