name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
jobs:
  build-api:
    runs-on: ubuntu-20.04
    steps:
      # Build
      - uses: actions/checkout@v2
      - name: Add remote
        run: git remote add publish_remote https://github.com/ihm-tswow/site-2.git
      - name: Create dummy commit file
        run: touch __dummy.txt
      - name: Commit build files
        run: git add . && git config user.name test && git config user.email test && git commit -m "Bump"
      - run: mkdir --parents "$HOME/.ssh"
      - run: echo "${{ secrets.SSH_DEPLOY_KEY}}" > "$HOME/.ssh/deploy_key"
      - run: export GIT_SSH_COMMAND='ssh -i $HOME/.ssh/deploy_key -o UserKnownHostsFile=$HOME/.ssh/known_hosts'
      - run: ssh-keyscan -H github.com > "$HOME/.ssh/known_hosts"
      - run: git push "git@github.com:ihm-tswow/site-2.git" -f HEAD:main